var includedCountriesICLab = [
	'United States of America',
	 'Korea, Republic of',
	 'Spain',
	 'South Africa',
	 'Czech Republic',
	 'Poland',
	 'Malaysia',
	 'Russia',
	 'China',
	 'Taiwan, Province of China',
	 'Bulgaria',
	 'Hong Kong',
	 'Romania',
	 'Peru',
	 'Hungary',
	 'Norway',
	 'Mexico',
	 'Ukraine',
	 'Netherlands',
	 'Vietnam',
	 'Japan',
	 'Lithuania',
	 'Serbia',
	 'Australia',
	 'Kenya',
	 'Slovakia',
	 'India',
	 'Chile',
	 'Canada',
	 'Liechtenstein',
	 'Singapore',
	 'Indonesia',
	 'New Zealand',
	 'Luxembourg',
	 'Belize',
	 'Colombia',
	 'Turkey',
	 'Brazil',
	 'Sweden',
	 'Iceland',
	 'Finland',
	 'Algeria',
	 'Portugal',
	 'Denmark',
	 'Israel',
	 'Moldova, Republic of',
	 'Austria',
	 'Seychelles'
];